export const GET_RECORD_DETAILS_REQUEST = 'GET_RECORD_DETAILS_REQUEST';
export const GET_RECORD_DETAILS_SUCCESS = 'GET_RECORD_DETAILS_SUCCESS';
export const GET_RECORD_DETAILS_FAILURE = 'GET_RECORD_DETAILS_FAILURE';
export const GET_PLAYER_INFORMATION_REQUEST = 'GET_PLAYER_INFORMATION_REQUEST';
export const GET_PLAYER_INFORMATION_SUCCESS = 'GET_PLAYER_INFORMATION_SUCCESS';
export const GET_PLAYER_INFORMATION_FAILURE = 'GET_PLAYER_INFORMATION_FAILURE';
