export const GET_RECORD_DETAILS_REQUEST = 'GET_RECORD_DETAILS_REQUEST';
export const GET_RECORD_DETAILS_SUCCESS = 'GET_RECORD_DETAILS_SUCCESS';
export const GET_RECORD_DETAILS_FAILURE = 'GET_RECORD_DETAILS_FAILURE';
